---
micronaut:
  application:
    name: transfers-service
---
kafka:
#  streams:
#    #Micronaut default
#    default:
#      #Kafka streams default
#      default:
#        key:
#          serde: org.apache.kafka.common.serialization.Serdes$UUIDSerde
#        value:
#          serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
  bootstrap:
    servers: localhost:9092
  schema:
    registry:
      url: http://localhost:8081
